#ifndef MAIN_TASK_COMMON_H
#define MAIN_TASK_COMMON_H

// Button task info
#define BUTTON_APP_TASK_STACK_SIZE 2048
#define BUTTON_APP_TASK_PRIORITY 5
#define BUTTON_APP_TASK_CORE_ID 1

#define BUTTON_STOP_MUSIC_TASK_STACK_SIZE 2048
#define BUTTON_STOP_MUSIC_TASK_PRIORITY 4
#define BUTTON_STOP_MUSIC_TASK_CORE_ID 1

// Buzzer task info
#define BUZZER_APP_TASK_STACK_SIZE 2048
#define BUZZER_APP_TASK_PRIORITY 5
#define BUZZER_APP_TASK_CORE_ID 0

#endif
